/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_AzrAxAQOn",
    "aws_user_pools_web_client_id": "722ndl5voecsrnip6vb1nj95tm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zx5fuiocxvco7b3fc74hnlz7vu.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
